In [9]:
!pip install matplotlib
import numpy as np
import matplotlib.pyplot as plt

print(np.__version__)

Defaulting to user installation because normal site-packages is not writeable
2.0.1


In [12]:
##
A = np.array([[2, 3, 4],
             [10,20,30]])

B = np.array([[2,3,4],
              [10,20,30]], dtype = np.float32)

print("Matrix A = \n", A)
print("Shape of A = ", A.shape)
print("Dtype A = ", A.dtype)

print("Matrix A = \n", B)
print("Shape of A = ", B.shape)
print("Dtype A = ", B.dtype)

Matrix A = 
 [[ 2  3  4]
 [10 20 30]]
Shape of A =  (2, 3)
Dtype A =  int64
Matrix A = 
 [[ 2.  3.  4.]
 [10. 20. 30.]]
Shape of A =  (2, 3)
Dtype A =  float32


In [25]:
## Diagonal
a = np.array([1, 2, 3, 4])

D_1 = np.diag(a)
print("D_1 = \n", D_1)

b= np.random.randint(1, 10, 5)
D_2 = np.diag(b)
print("D_2 = \n", D_2)

D_1 = 
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
D_2 = 
 [[8 0 0 0 0]
 [0 8 0 0 0]
 [0 0 8 0 0]
 [0 0 0 9 0]
 [0 0 0 0 1]]


In [24]:
## 단위 행렬, Identity
I_3 = np.eye(3)
print("3 x 3 Identity = \n", I_3)

I_5 = np.eye(5)
print("5 x 5 Identity = \n", I_5)

3 x 3 Identity = 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
5 x 5 Identity = 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [22]:
## 전치 행렬, Matrix transpose
A = np.array([[1, 2, 3, 4],
             [5, 6, 7, 8]], dtype = np.int64)
print("A = \n", A)
print("transpose A = \n", A.T)

A = 
 [[1 2 3 4]
 [5 6 7 8]]
transpose A = 
 [[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [31]:
## Matrix product

A = np.array([[1, 2],
             [3, 4]])
B = np.array([[1, 1],
             [1, 2]])
# 원소끼리 곱하는 프로덕트
print("A*B = \n", A*B)
print("A X B = \n", np.matmul(A, B)) # .matmul 텐서도 맷플랏도 뭣도 matmul명령어 같다?

A*B = 
 [[1 2]
 [3 8]]
A X B = 
 [[ 3  5]
 [ 7 11]]
