In [1]:
# pandas numpy matpltlib seaborn 라이브러리 설치
%pip install numpy
%pip install pandas
%pip install matplotlib
%pip install seaborn
%pip install sklearn
# 주피터노트북에서는 !pip 대신 %pip install 사용

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.
Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.
Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.
Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


---
# Numpy
---

데이터 과학 분야에서 방대한 데이터 처리, 딥러닝 운용의 기반이 되는 파이썬 라이브러리  
대규모 다차원 배열, 행렬 데이터 처리를 위한 수치 연산을 지원  
내부적으로 C언어로 구현이 되어있어 속도가 매우빠르고 메모리를 최소한으로 유지  

In [1]:
import numpy as np

In [17]:
# 1,2,3차원 배열 생성
ar = [1,2,3],  [[1,2,3],[4,5,6]],  [[[1,2,3],[4,5,6],[7,8,9]]]
for i in map(np.array, ar): print(i)

# 배열 축 차원 행렬 텐서

# 차원과 크기 변경
# np.reshape()
# 데이터 세트 선택 인덱싱
# 행렬의 정렬
# np.sort()
# np.argsort()
# 선형대수 연산 - 행렬 내적과 전치행렬
# 배열 간 사칙연산
# Broadcasting
# 집계(Aggregation)
    # 합계
    # 평균
    # 곱셈
    # 최대값 최솟값
    # 표준편차와 분산


[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
<class 'numpy.ndarray'>


---
# Pandas
---

In [2]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
# pyarrow 가 뭐였나 서치
# pd
# pd.__version__
# np
# np.__version__ㅌ
# sns
# sns.__version__
# sklearn
# sklearn.__version__
# 설치 경로와 버전확인

In [3]:
# dict Series 변환
dict_data = {'a': 1, 'b': 2, 'c': 3}
sr = pd.Series(dict_data)
print(sr, type(sr))
sr
# 키값은 행인덱스 시리즈는 열이 된다.

a    1
b    2
c    3
dtype: int64 <class 'pandas.core.series.Series'>


a    1
b    2
c    3
dtype: int64

In [4]:
# list Series 변환
lst_data = ['2024-09-09', 3.14, 'ABC', 100, True]
sr  = pd.Series(lst_data)
print('sr:\n',sr)
print('sr.index:',sr.index, # 인덱스 배열
      '\nsr.values:', sr.values, # 데이터 값 배열
      '\nsr.dtype:', sr.dtype, # 구성 원소 자료형
      '\nlen(sr):', len(sr), # 배열의 크기
      '\nsr.shape:', sr.shape, # 배열의 형태 : (5, ) 1차원에 5개요소
      '\nsr.ndim:', sr.ndim, # 배열의 차원 : 1차원
      )

sr:
 0    2024-09-09
1          3.14
2           ABC
3           100
4          True
dtype: object
sr.index: RangeIndex(start=0, stop=5, step=1) 
sr.values: ['2024-09-09' 3.14 'ABC' 100 True] 
sr.dtype: object 
len(sr): 5 
sr.shape: (5,) 
sr.ndim: 1


In [5]:
# numpy 배열 Series 변환
np_array = np.array(lst_data)
print('np_array:\n',np_array)
np_sr = pd.Series(np_array, index=['생년월일', 'pi', '알파벳', '정수', '참'])
print('np_sr.index:',np_sr.index, # 인덱스 배열
      '\nsr.values:', np_sr.values, # 데이터 값 배열
      '\nsr.dtype:', np_sr.dtype, # 구성 원소 자료형
      '\nlen(np_sr):', len(np_sr), # 배열의 크기
      '\nsr.shape:', np_sr.shape, # 배열의 형태 : (5, ) 1차원에 5개요소
      '\nsr.ndim:', np_sr.ndim, # 배열의 차원 : 1차원
      )

np_array:
 ['2024-09-09' '3.14' 'ABC' '100' 'True']
np_sr.index: Index(['생년월일', 'pi', '알파벳', '정수', '참'], dtype='object') 
sr.values: ['2024-09-09' '3.14' 'ABC' '100' 'True'] 
sr.dtype: object 
len(np_sr): 5 
sr.shape: (5,) 
sr.ndim: 1


In [6]:
# 원소 선택
print('\nnp_sr.iloc[0]:\n',np_sr.iloc[0])
print('\nnp_sr.iloc[[1,3]]:\n',np_sr.iloc[[1,3]])
print("\nnp_sr.loc['생년월일']:\n",np_sr.loc['생년월일'])
print("\nnp_sr.loc[['생년월일','정수']]:\n",np_sr.loc[['생년월일','정수']])

print("\nnp_sr.loc['생년월일':'정수']:\n",np_sr.loc['생년월일':'정수'])


np_sr.iloc[0]:
 2024-09-09

np_sr.iloc[[1,3]]:
 pi    3.14
정수     100
dtype: object

np_sr.loc['생년월일']:
 2024-09-09

np_sr.loc[['생년월일','정수']]:
 생년월일    2024-09-09
정수             100
dtype: object

np_sr.loc['생년월일':'정수']:
 생년월일    2024-09-09
pi            3.14
알파벳            ABC
정수             100
dtype: object
