## ① 인공 신경망에 대하여 🧠







<img src='https://datadiving.dothome.co.kr/Deep_1-9.png' width = '600' border='0'></a>


✏️ **학습 방법에 따라서 인공지능 → 머신러닝 → 딥러닝으로 구체화됩니다.**
> **`인공지능`** </br>
> 인공지능은 인간의 지능이 갖고 있는 기능을 갖춘 컴퓨터 시스템이며, 인간의 지능을 기계 등에 인공적으로 시연(구현)한 가장 큰 범주에 해당합니다. </br>일반적으로 범용 컴퓨터에 적용한다고 가정합니다.

> **`머신러닝`** </br>기계 학습 또는 머신 러닝은 인공지능의 한 분야로, 컴퓨터가 학습할 수 있도록 하는 알고리즘과 기술을 개발하는 분야를 말합니다.

> **`딥러닝(심층학습)`** </br> 여러 비선형 변환기법의 조합을 통해 높은 수준의 추상화를 시도하는 기계 학습 알고리즘의 집합으로 정의됩니다. </br>큰 틀에서 사람의 사고방식을 컴퓨터에게 가르치는 기계학습의 한 분야라고 이야기할 수 있습니다. </br>딥 러닝은 특징 추출부터 패턴까지 모든 과정을 사람의 개입 없이 심층인공신경망을 토대로 학습방식을 구현하는 기술입니다.

**인공 신경망(artificial neural network)**은 알고리즘의 플로우 차트(순서도)와 매우 유사합니다.

다만, 훨씬 더 단순하죠. 오직 동그라미와 화살표만으로 이루어져 있고, 대칭적입니다.

<img src='https://datadiving.dothome.co.kr/Deep_1-10.jpeg' width='600' border='0'></a>



```
🔎 인공 신경망의 하나의 동그라미를 확대해 봅시다.  

```
<img src='https://datadiving.dothome.co.kr/Deep_1-11.png' width='600' border='0'></a>

<img src='https://datadiving.dothome.co.kr/Deep_1-12.png' border='0'></a>

입력 x와 딥러닝을 통해 찾아지는 숫자 w가 서로 곱해지고 더해져서 하나의 숫자를 만들고 단순한 함수 f를 통과하여 다음 동그라미의 입력으로 넘어갑니다.

이러한 구조를 **퍼셉트론(perceptron)**이라고 합니다.

모든 인공지능 알고리즘은 이러한 구조로 이뤄져 있고,

이러한 신경망을 통해 학습(learn)을 하는 것을 **딥러닝**이라고 합니다.

### 딥러닝이란?
```
🧐 이제 본격적으로 딥러닝에 대해 탐구해봅시다!
```

앞서, **인공 신경망을 통해 학습하는 과정**이 딥러닝이라는 것을 배웠습니다.

기존 프로그램의 한계는 바로 사람이 짜기 때문에 생긴다는 것도 배웠죠!

따라서 딥러닝은 기존 프로그래밍처럼 프로그래머가 정해진 규칙에 기반한 알고리즘을 지정해주지 않고    

가장 단순한 구조의 플로우 차트에서 출발하여 **데이터 기반으로 스스로 배우는 과정**을 의미합니다.    

```
🗂 데이터를 기반으로 스스로 학습하는 과정을 구체적으로 살펴볼까요?
```

<img src='https://datadiving.dothome.co.kr/Deep_1-13.jpeg' border='0'></a>

임의의 w (weight) 로 구성된 인공 신경망에서 각 w 값을 키웠다가, 줄였다가 변화시키면서

**최종 결과값이 기대하는 값에 가까워지는 방향**으로 w 를 학습하게 됩니다.  

우리가 아는 알파고, 자율 주행, 아무리 복잡한 딥러닝 알고리즘도 이러한 단순 구조의 퍼셉트론들의 집합으로 이뤄져 있습니다.   


## Pytorch 설치 및 확인



In [ ]:
!pip install torch

In [4]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.4.1+cpu
False


## Pytorch Tensor

pytorch의 가장 근본이 되는 Tensor들에 대해서 배워보겠습니다.


### Tensor?

먼저, Tensor에 대해 알아봅시다.

```Tensor란?```  **다차원의 배열**을 뜻하는 말입니다.

*배열의 차원에 따라 불리는 이름이 달라진다는 것, 모두 알고 계시죠?</br>
0차원은 스칼라, 1차원은 벡터, 2차원은 메트릭스, 그 이상의 다차원은 아래 차원의 것을 모아놓은 배열인 것이라고 할 수 있는데요!</br> tensor는 스칼라, 벡터, 매트릭스 등의 데이터와 그 이상의 고차원 데이터도 포함하는 개념입니다.

참고로 tensor에서 Rank는 그 데이터가 몇 차원의 배열인지를 의미합니다.




<img src='https://datadiving.dothome.co.kr/Deep_1-63.jpeg' width='900'  border='0'></a>

### Tensor 만드는 법 1

torch.tensor(data): data는 튜플, 리스트, numpy 배열 등등


In [ ]:
# 0-D Tensor
# 텐서를 생성하는 함수를 작성하시오.
scalar = torch.tensor(5.0)
number = torch.tensor(1.0)
print(scalar)  # tensor(5.)
print(number) # tensor(1.)

In [ ]:
# 텐서를 생성하는 함수를 작성하시오.
vector = torch.tensor([1.0, 2.0, 3.0])
tuple_vector = torch.tensor((1, 2, 3))
print(vector)  # tensor([1., 2., 3.])
print(tuple_vector) # tensor([1, 2, 3,])

In [ ]:
matrix = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
matrix2 = torch.tensor([[1, 2, 3], [3, 4, 5]])
print(matrix.shape)
print(matrix2.shape)
# tensor([[1., 2.],
#         [3., 4.]])

In [ ]:
matrix2 = [[1, 2, 3], [3, 4, 5]]
lst = [matrix2, matrix2, matrix2, matrix2]

tensor_3d = torch.tensor([[[1.0], [2.0]], [[3.0], [4.0]]])
tensor_3d_2 = torch.tensor(lst) # len(lst), len(lst[0]), len(lst[0][0]), ....
print(tensor_3d_2.shape)

### torch.tensor의 주요 속성들

- tensor.shape
- tensor.size()
- tensor.dtype
- device: gpu에 있는지, cpu에 있는지
- requires_grad: 이게 True면 미분값을 계산함. 아니면 하지 않음.


In [ ]:
#텐서의 크기를 출력해보는 코드를 작성하시오
print(vector.shape)    # torch.Size([3])
print(matrix.size())   # torch.Size([2, 2])
print(tensor_3d.shape) # torch.Size([2, 2, 1])

In [ ]:
#텐서의 데이터 타입을 출력하는 코드를 작성하시오
print(vector.dtype)    # torch.float32
int_tensor = torch.tensor([1, 2, 3], dtype=torch.int32)
print(int_tensor.dtype)  # torch.int32

#텐서가 현재 gpu에 위치해 있는지 확인하는 코드를 작성하시오
device = 'cuda'*torch.cuda.is_available() or 'cpu'
tensor_gpu = torch.tensor([1.0, 2.0, 3.0]).to(device)
print(tensor_gpu.device)  # cuda:0 or cpu

### torch.tensor 만드는 방법 2

- torch.tensor(data)
- 자주 쓰는 텐서들은 만드는 함수가 있음.
  * torch.zeros(size): size 형태로 된, 0으로 된 텐서를 만듬.
  * torch.ones(size): size 형태로 된, 1로 된 텐서를 만듬.
  * torch.rand(size) / torch.randn(size) : 랜덤한 숫자로 된 텐서를 만듬. rand는 0과 1 사이에서 랜덤하게, randn은 표준정규분포(평균 0, 표준편차 1)에서 뽑아옴.
  * torch.eye(n): 대각선만 1이고 이외에는 0인 2D 텐서(행렬)을 만듬.
- 이외에도 많이 쓰이는 함수들
  * torch.arange: range() 함수와 매우 비슷하다.
  * torch.linspace(start, end, steps): start부터, end까지, steps개의 숫자를 가지는 텐서를 만듬. 이 때, 숫자들은 등간격으로 만들어짐.


In [ ]:
list_tensor = torch.tensor([1, 2, 3])
tuple_tensor = torch.tensor((4, 5, 6))

#값이 0인 텐서를 생성하는 코드를 작성하시오
zeros = torch.zeros((2, 3))
#값이 1인 텐서를 생성하는 코드를 작성하시오
ones = torch.ones((2, 3))
#값이 랜덤인 텐서를 생성하는 코드를 작성하시오
rand = torch.rand((2, 3))
eye = torch.eye(3)  # 3x3 Identity matrix
print(zeros)
print(ones)
print(rand)
print(eye)
#랜덤값의 분포가 정규분포인 텐서를 생성하는 코드를 작성하시오
normal = torch.randn((2, 3))  # Normal distribution

 # 값이 range(0, 10, 2) 인 텐서를 생성하는 코드를 작성하시오
arange_tensor = torch.arange(start=0, end=10, step=2)
 # # 0 0.25 0.5 0.75 1 처럼 등분으로 나뉘는 텐서를 생성하는 코드를 작성하시오
linspace_tensor = torch.linspace(start=0, end=1, steps=5) # 0 0.25 0.5 0.75 1
print(arange_tensor)
print(linspace_tensor)
float_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float64)
int_tensor = torch.tensor([1, 2, 3], dtype=torch.int32)


TODO: 위 각 함수들을 torch.tensor와 파이썬 리스트 operation들을 이용하여 재구현해 보세요.

In [ ]:
# write your code here
import random

def nested_list(shape, value = 0):
    """Accepts tuple/list of int, denoting shape of the nested list.
    """
    if len(shape) == 1:
        l = shape[0]
        return [value for _ in range(l)]
    else:
        l = shape[0]
        return [nested_list(shape[1:], value = value) for _ in range(l)]

def random_nested_list(shape, sample_from, *args):
    if len(shape) == 1:
        l = shape[0]
        return [sample_from(*args) for _ in range(l)]
    else:
        l = shape[0]
        return [random_nested_list(shape[1:], sample_from, *args) for _ in range(l)]
'''
def random_nested_list(shape):
    """Accepts tuple/list of int, denoting shape of the nested list.
    """
    if len(shape) == 1:
        l = shape[0]
        return [random.random() for _ in range(l)]
    else:
        l = shape[0]
        return [random_nested_list(shape[1:]) for _ in range(l)]
'''
def randomn_nested_list(shape):
    """Accepts tuple/list of int, denoting shape of the nested list.
    """
    if len(shape) == 1:
        l = shape[0]
        return [random.gauss(0, 1) for _ in range(l)]
    else:
        l = shape[0]
        return [randomn_nested_list(shape[1:]) for _ in range(l)]

def zeros(shape):
    return torch.tensor(nested_list(shape, value = 0))

def ones(shape):
    return torch.tensor(nested_list(shape, value = 1))

def rand(shape):
    return torch.tensor(random_nested_list(shape, random.random))

def randn(shape):
    return torch.tensor(random_nested_list(shape, random.gauss, 0, 1))

print(nested_list((2, 3, 4), value = 0))
print(zeros((2,3,4)) == torch.zeros((2,3,4)))
print(ones((2,3,4)))
print(rand((2,3,4)))
print(randn((2,3,4)))

def eyes(n):
    lst = [[0 for i in range(n)] for j in range(n)]

    lst = []
    for i in range(n):
        tmp = []
        for j in range(n):
            tmp.append(0)
        lst.append(tmp)

    for i in range(n):
        lst[i][i] = 1

    return torch.tensor(lst)

print(eyes(10))

### torch.tensor끼리의 연산

일반적인 사칙연산, 행렬 곱(matmul), 원소간 곱 등등이 다 적용됨.

In [ ]:
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

add = a + b  # tensor([5., 7., 9.])
sub = a - b  # tensor([-3., -3., -3.])

mul = a * b  # tensor([ 4., 10., 18.])
div = b / a  # tensor([4.0000, 2.5000, 2.0000])

exp = a ** 2  # tensor([1., 4., 9.])

In [ ]:
matrix_a = torch.tensor([[1, 2], [3, 4]])
matrix_b = torch.tensor([[5, 6], [7, 8]])
'''
1 2  5 6
3 4  7 8

1 3
2 4
'''
'''
1*5 + 2*7 = 19   1*6 + 2*8 = 22
3*5 + 4*7 = 43   3*6 + 4*8 = 50
'''

#행렬곱을 수행하는 코드
matmul = torch.????(matrix_a, matrix_b)

# tensor([[19, 22],
#         [43, 50]])

elem_mul = matrix_a * matrix_b
# tensor([[ 5, 12],
#         [21, 32]])

# 축을 바꾸는 전치를 수행하는 코드
transposed = torch.????(matrix_a, 0, 1)
# 주로 딥러닝이나 배열 연산에서 사용되며, 다차원 배열 또는 텐서의 축을 바꿔주는 역할
# tensor([[1, 3],
#         [2, 4]])

print(torch.matmul(torch.tensor([[1],[2],[3]]), torch.tensor([[4,5,6]])))


### Broadcasting

브로드캐스팅은 서로 다른 크기를 가진 텐서들 간에 연산을 수행할 때, 자동으로 크기를 맞춰주는 PyTorch(및 NumPy)의 기능입니다. 이 기능은 명시적으로 텐서의 크기를 변환하지 않아도, 작은 크기의 텐서를 큰 크기의 텐서와 함께 연산할 수 있도록 해줍니다. Pandas나 Numpy 등에서도 자주 활용되기 때문에 알아두면 좋습니다.

브로드캐스팅 규칙:
1. 차원의 맞추기: 두 텐서의 차원(Dimension) 수가 다를 때, 차원이 작은 텐서의 앞쪽에 1을 추가하여 차원을 맞춥니다.
2. 크기 맞추기: 각 차원에서 크기가 1인 텐서는 해당 차원의 크기를 큰 텐서의 크기에 맞춰 늘릴 수 있습니다.
3. 불가능한 경우: 두 텐서가 특정 차원에서 서로 다른 크기를 가지며, 그중 하나가 1이 아니면 브로드캐스팅이 불가능하고 오류가 발생합니다.

예를 들어서,

- (2,3) 크기의 텐서에 (3,) 크기의 텐서를 더하면, (2,3) 크기의 텐서가 됩니다. 이 때 (3,) 크기의 텐서들은 첫 번째 차원에 대해서 다 더해집니다.


In [ ]:
# shape (1, 3) / (3, 1)
# dim = 0
# 3 / 3
# dim = 1
# 3 / 3

#

In [ ]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]])    # Shape: (2, 3,)
b = torch.tensor([1, 2, 3])                 # Shape: (3,)
b = torch.tensor([[1, 2, 3]])               # Shape: (1, 3,)
b = torch.tensor([[1, 2, 3], [1, 2, 3]])    # Shape: (2, 3,)

broadcast_add = a + b  # Shape: (2, 3)
# tensor([[2, 4, 6],
#         [5, 7, 9]])

a = torch.tensor([[1], [2], [3]])  # Shape: (3, 1)
b = torch.tensor([4, 5, 6])        # Shape: (3,)
b = torch.tensor([[4, 5, 6]])        # Shape: (1, 3,)
b = torch.tensor([[4, 5, 6], [4, 5, 6], [4, 5, 6]])        # Shape: (3, 3,)
a = torch.tensor([[1, 1, 1], [2, 2, 2], [3, 3, 3]])  # Shape: (3, 3)
a*b = [[4, 5, 6], [8, 10, 12], [12, 15, 18]]
# To make shapes compatible:
# a: (3, 1) -> (3, 3)
# b: (3,)   -> (1, 3) -> (3, 3)

broadcast_mul = a * b  # Shape: (3, 3)
# tensor([[ 4,  5,  6],
#         [ 8, 10, 12],
#         [12, 15, 18]])

### 오늘의 복습용 문제

1. l = list of list of .... 를 받아서, 하는 함수 get_shape를 작성하세요.
  - 여기서 torch.tensor(l).shape 과 같은 값을 가지는 리스트를 반환
  - 만약 torch.tensor가 불가능하다면 False를 리턴
2. l = list of list of ..., r = list of list of ... 두 input을 받아서, 아래와 같이 동작하는 함수 broadcasting을 작성하세요
  - 브로드캐스팅이 될 때 각 l, r이 바뀌어야 하는 형태를 리턴
  - 브로드캐스팅이 되지 않으면 False를 리턴

[[1,2,3], [1,2]]

In [ ]:
def get_shape(lst):
    res = []
    cur = lst

    while isinstance(cur, list):
        res.append(len(cur))
        cur = cur[0]

    return res

def get_shape(lst):
    if not isinstance(lst, list):
        return []
    else:
        shapes = []
        for elem in lst:
            shape = get_shape(elem)
            if shape not in shapes:
                shapes.append(shape)
        if len(shapes) == 1:
            return [len(lst)] + get_shape(lst[0])
        else:
            return False

def fill(l, r):
    """If len(l) > len(r), fill 1 to r's front, so that len(l) == len(r),
    If len(r) < len(l), do the opposite.
    """
    if len(l) > len(r):
        diff = len(l) - len(r)
        r = [1 for _ in range(diff)] + r
        return l, r
    elif len(l) < len(r):
        diff = len(r) - len(l)
        l = [1 for _ in range(diff)] + l
        return l, r
    return l, r

def expand_dimension(l, dim_idx, r_s):
    """
    l = [[1,2,3,]] (shape 1, 3)
    dim_idx = 0
    r_s = 4
    expand_dimension(l, 0, 4)
    >> [[1,2,3,], [1,2,3,], [1,2,3,], [1,2,3,]]

    l = [[[1,2,3]], [[1,2,3]], [[1,2,3]]] (shape 3, 1, 3 -> 3, 2, 3)
    l[0] = [[1,2,3]], l[1], l[2] (shape 2, 3)
    dim_idx = 1
    r_s = 2
    expand_dimension(l, 0, 2)
    >> [[[1,2,3], [1,2,3]], [[1,2,3], [1,2,3]], [[1,2,3], [1,2,3]]] (shape 3, 2, 3)

    l / shape 4, 3, 2, 1, 2 -> 4, 3, 2, 5, 2
    expand_dimension(l, 3, 5)
    l[0], l[1], l[2], l[3] / shape 3, 2, 1, 2 -> 3, 2, 5, 2
    expand_dimension(l[0], 2, 5)
    expand_dimension(l[1], 2, 5)
    expand_dimension(l[2], 2, 5)
    expand_dimension(l[3], 2, 5)
    """
    assert get_shape(l)[dim_idx] == 1, (get_shape(l), dim_idx)

    if dim_idx == 0:
        return [l[0] for _ in range(r_s)]
    else:
        return [expand_dimension(e, dim_idx - 1, r_s) for e in l]


def broadcasting(l, r):
    shape_l = get_shape(l)
    shape_r = get_shape(r)

    assert shape_l and shape_r

    # 차원의 맞추기: 두 텐서의 차원(Dimension) 수가 다를 때,
    # 차원이 작은 텐서의 앞쪽에 1을 추가하여 차원을 맞춥니다.

    # (2, 3) / (4, 5, 2, 3) -> (1, 1, 2, 3) / (4, 5, 2, 3)

    l_is_bigger = False
    r_is_bigger = False
    diff = abs(len(shape_l) - len(shape_r))

    if len(shape_l) > len(shape_r):
        l_is_bigger = True
    elif len(shape_l) < len(shape_r):
        r_is_bigger = True

    shape_l, shape_r = fill(shape_l, shape_r)

    for _ in range(diff):
        if l_is_bigger:
            r = [r]  # r.shape: a1, a2, ... , an / [r].shape : 1, a1, a2, ... , an
        elif r_is_bigger:
            l = [l]

    assert shape_l == get_shape(l)
    assert shape_r == get_shape(r)

    # 크기 맞추기: 각 차원에서 크기가 1인 텐서는
    # 해당 차원의 크기를 큰 텐서의 크기에 맞춰 늘릴 수 있습니다.

    dim_idx = 0

    for l_s, r_s in zip(shape_l, shape_r):
        if l_s != r_s:
            if min(l_s, r_s) == 1:
                if l_s == 1: #
                    l = expand_dimension(l, dim_idx, r_s)
                else: # r_s == 1
                    r = expand_dimension(r, dim_idx, l_s)
            else:
                return False
        dim_idx += 1

    return l, r

l = [[[1,2,3]], [[1,2,3]], [[1,2,3]]]
print("get_shape(I) :", get_shape(l))

r = [[1,2,3,], [1,2,3,], [1,2,3,], [1,2,3,]]
print(get_shape(r))

# 3 1 3 / 4 3 -> 3 1 3 / 1 4 3 -> 3 1 3 / 3 4 3 -> 3 4 3 / 3 4 3
# r = [[[1,2,3,], [1,2,3,], [1,2,3,], [1,2,3,]]]
r_ans = [[
            [1,2,3,],
            [1,2,3,],
            [1,2,3,],
            [1,2,3,]
          ],
         [[1,2,3,], [1,2,3,], [1,2,3,], [1,2,3,]],
         [[1,2,3,], [1,2,3,], [1,2,3,], [1,2,3,]]]
l_ans = [[[1,2,3], [1,2,3], [1,2,3], [1,2,3]],
         [[1,2,3], [1,2,3], [1,2,3], [1,2,3]],
         [[1,2,3], [1,2,3], [1,2,3], [1,2,3]]]
l, r = broadcasting(l, r)
print(get_shape(l), get_shape(r))
print(l_ans == l, r_ans == r)

### 이 외 tensor operation들

- Slicing / Indexing
- Reshaping
- Concatenation / Stacking

In [ ]:
# slicing / indexing
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Basic indexing
element = tensor[1, 2]  # tensor(6)

# Slicing
sub_tensor = tensor[:, 1:]  # tensor([[2, 3],
                            #         [5, 6],
                            #         [8, 9]])

# Advanced indexing with masks
mask = tensor > 5
filtered = tensor[mask]  # tensor([6, 7, 8, 9])

In [ ]:
# reshaping

tensor = torch.arange(0, 12)
reshaped_view = tensor.view(3, 4)  # tensor([[ 0,  1,  2,  3],
                                   #         [ 4,  5,  6,  7],
                                   #         [ 8,  9, 10, 11]])

reshaped_reshape = tensor.reshape(2, 6)  # tensor([[ 0,  1,  2,  3,  4,  5],
                                         #         [ 6,  7,  8,  9, 10, 11]])

# tensor.permute
tensor = torch.randn(2, 3, 4)
permuted = tensor.permute(2, 0, 1)  # Changes the order of dimensions
print(permuted.shape)  # torch.Size([4, 2, 3])


In [ ]:
tensor

In [9]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# Concatenate along existing dimension
concat = torch.cat((a, b), dim=0)  # tensor([1, 2, 3, 4, 5, 6])

# Stack along a new dimension
stack = torch.stack((a, b), dim=0)
# tensor([[1, 2, 3],
#         [4, 5, 6]])

stack = torch.stack((a, b), dim=1)
# tensor([[1, 4],
#         [2, 5],
#         [3, 6]])

tensor([1, 2, 3, 4, 5, 6]) 
 tensor([[1, 4],
        [2, 5],
        [3, 6]])


### 수학적 함수들

- abs, sqrt, exp, log 등 unary 함수들 (텐서 하나만을 input으로 받음): torch.abs, torch.sqrt, torch.exp, torch.log
- max, min 등 binary 함수들 (텐서 2개를 input으로 받음): torch.max, torch.min
- 차원을 하나 혹은 여럿 낮추는 Reduction Operation들: torch.sum(tensor, dim = n)


In [ ]:
a = torch.tensor([-1.0, -2.0, 3.0])

abs_a = torch.abs(a)          # tensor([1., 2., 3.])
# sqrt_a = torch.sqrt(a)
sqrt_a = torch.sqrt(torch.abs(a))  # tensor([1., 1.4142, 1.7321])
exp_a = torch.exp(a)          # tensor([0.3679, 0.1353, 20.0855])
log_a = torch.log(torch.abs(a))    # tensor([0.0000, 0.6931, 1.0986])

In [ ]:
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

max_ab = torch.max(a, b)  # tensor([4., 5., 6.])
min_ab = torch.min(a, b)  # tensor([1., 2., 3.])


In [ ]:
tensor = torch.tensor([[1, 2, 3], [3, 4, 5]]) # (2,3)

sum_all = torch.sum(tensor)          # tensor(10)
sum_dim0 = torch.sum(tensor, dim=0)  # tensor([4, 6, 8]) (3,)
sum_dim1 = torch.sum(tensor, dim=1)  # tensor([6, 12]) (2,)

mean_all = torch.mean(tensor.float(), dim = 1)  # tensor(2.5000)
print(mean_all)

In [ ]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([2, 2, 2])

greater = a > b  # tensor([False, False, True])
equal = a == b   # tensor([False, True, False])


## Pytorch로 다시 해 보는 선형회귀

주어진 데이터 $(x_i, y_i)$ 에 대해서 $y=wx+b$에서, 가장 적절한 w와 b를 찾는 것이 선형회귀였음.

y = wx + b 에서, w와 b는 parameter이고 x는 입력, y는 출력임.
이 때 w랑 b를 구하기 위해서, 다음의 loss function을 최소화하는 방향으로 학습하고 싶다고 하자.

$ MSE = \frac{1}{n} \sum_{i=1}^{n} (y_i - \hat{y}_i)^2 $

원래는 저 값을 그냥 바로 식으로 계산할 수 있었지만, 언제나 그렇지는 않기 때문에 (선형회귀 외의 다른 모델들에서) 수치적으로 계산해보자.




In [35]:
# 임의로 데이터를 한번 만들어 보자.
# True parameters
true_w = 2.0
true_b = 1.0

# Generate data
# 표준 정규분포 텐서 랜덤 생성하는 코드가 뭐였죠?
X = torch.randn(100, 1) * 10  # 100 samples, single feature
y = true_w * X + true_b + torch.randn(100, 1) * 0.2  # Add noise

# y[0]= true_w * X[0] + true_b + torch.randn(1, 1) * 2
# y[1]= true_w * X[1] + true_b + torch.randn(1, 1) * 2
# ...
# y[99]= true_w * X[99] + true_b + torch.randn(1, 1) * 2

### requires_grad = True ??

- 다음과 같이 경사하강법을 통해 학습을 할때 미분을 통해 나오는 '기울기' 값을 저장을 해야합니다.

- requires_grad = True 를 해야 기울기가 저장됩니다.

<img src='https://raw.githubusercontent.com/angeloyeo/angeloyeo.github.io/master/pics/2020-08-16-gradient_descent/pic1.png' width='500'  border='0'></a>

In [36]:
# requires_grad = True로 해야 학습이 가능

# 기울기를 기록하는 코드 작성
w = torch.randn(1, 1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

### learning_rate??? 뭐였지??

- lr (learning_rate): 학습율, 경사하강법에서 파라미터를 업데이트하는 정도를 조절하기 위한 변수,</br> *보통 0.0001~0.001의 학습율을 사용합니다.

✨학습율이 크다고 항상 좋은 것이 아닙니다!

<img src="https://datadiving.dothome.co.kr/Deep%202-1_6.png" width=900>

In [37]:
learning_rate = 0.009
epochs = 5000

In [ ]:
#epoch은 이 데이터를 몇바퀴 돌려서 학습을 시킬 것이냐! 라고 볼 수 있겠죠? 기억나시나요?
for epoch in range(epochs):
    #우리는 y을 예측하고 싶습니다. y에 영향을 주는 변수는 X하나 라고 생각하고 간단한 선형식을 만들어 보았습니다!
    y_pred = X * w + b # y_pred: 100, 1


    # Compute and print loss
    # loss 함수로 우리는 MSE 평균제곱오차의 식을 사용합니다.
    # 모듈을 불러올 수 있겠지만 수학식으로 작성하면 다음과 같습니다.
    # 예상한 값 - 실제값의 제곱의 평균
    loss = torch.mean((y_pred-y)**2)# 100, 1


    # 100 에폭당 우리는 지금 학습이 어느정도 되고 있는지 수치로 보고 싶어요!
    # 그래서 if%100이 0일때 print 해보는 코드를 짜보았습니다.
    if epoch % 100 == 0:
        print(f'Epoch {epoch}: w = {w.item():.4f}, b = {b.item():.4f}, loss = {loss.item():.4f}')
    # Forward pass: compute predicted y
    # 100, 1 / 1 -> 100, 1 / 1, 1 -> 100, 1 / 100, 1


    # Backward pass: compute gradients
    # 역전파를 통해 기울기를 계산합니다.
    # loss 는 우리가 위에 정의했던 'torch.mean((y_pred - y) ** 2)' 이었습니다!
    # 여기서 기울기를 계산하게 되면 독립변수(X) 에 영향을 주었던 w, b 에 대해서 기울기 값이 나오게 됩니다.
    loss.backward()

    # Update parameters using gradient descent
    # 잠깐 ! 여기서 왜 - 를 할까요?
    # 위 그림에서 우리는 기울기가 음수이면 \ 양수이면 / 모양을 띄는 것을 확인할 수 있었습니다.
    # 우리는 경사하강법 그래프에서 볼 수 있든 최저점을 찾아가야 하는데
    # 그럼 기울기가 음수이면 오른쪽 양수이면 왼쪽으로 가야하겠죠?
    # 즉 음수이면 그래프상 X축 기준으로 + 양수이면 X축 기준으로 - 를 해야하는 것 입니다.이걸 어떻게 할까요?
    # 바로 -연산을 하면 됩니다. -에 -를 하면 +가 되는 것은 아시죠?
    # 그래서 기울기가 음수일 경우 빼주면 +가 되어 오른쪽으로 이동하고 기울기가 양수일때 빼주면 왼쪽으로 이동하게 되는 것이죠!
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad

    # Zero gradients after updating
    # 그리고 이후 학습을 위해 기울기를 초기화 시켜줍니다.
    w.grad.zero_()
    b.grad.zero_()
    
    if epoch % 200 == 0:
        print(f'Epoch {epoch}: w = {w.item():.4f}, b = {b.item():.4f}, loss = {loss.item():.4f}')
    

TODO: 위 선형회귀 부분을 함수로 만들고, 다양한 하이퍼파라미터 (여기서의 hyperparameter은 learning rate 뿐임)를 바꿔가며 최적의 모델을 찾아보세요.


### 선형회귀 조금 더 해보기


TODO: 이번에는 비슷하게, 입력이 3개이고 출력이 1개인 선형회귀를 해 보자.

$y = w_1 x_1 + w_2 x_2 + w_3 x_3 + b$

In [ ]:
# y = w1*x1 + w2 * x2 + w3 * x3 + b


## 딥러닝 들어가기


아래 코드는 pytorch 에서 딥러닝 모델을 짤 때, 가장 일반적인 형식이라고 할 수 있다. 각 부분에서 쓰일 함수들은 문제에 따라서 다르지만, 대개의 경우 위 내용이 크게 바뀌지 않을 것임.

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
import torch.nn.functional as F
import numpy as np

# Seed for reproducibility
# 랜덤 시드를 고정하는 이유는 고정하지 않으면 매번 다른 값이 나와 모델을 튜닝할때 적절하지 않습니다.
# 모델 튜닝을 같은 기준, 환경에서 튜닝을 하기 위함입니다.
torch.manual_seed(0)
np.random.seed(0)

원래대로라면 실제 데이터를 쓰는 것이 좋지만, 실험의 편리함을 위해 인공적으로 만든 합성 데이터를 사용하자.

입력 feature는 20개다. 1시간 후에 비가 올지 안 올지 알고 싶은데, 현재 가지고 있는 데이터가 서울 각지의 습도 데이터라고 하자. 20곳에서 동시에 각각 습도를 잰 것이다. 이 데이터를 가지고 비가 오면 1, 비가 오지 않으면 0이라고 하자. 실제 데이터를 안 가지고 있기 때문에, 적당히 수식을 써서 비가 오는 경우와 안 오는 경우를 임의로 구분하여 합성 데이터를 만들자. 이러한 데이터 포인트 1000개를 만들자.



In [46]:
import numpy as np
import torch

# Generate synthetic data
num_samples = 1000
input_features = 20 #20개의 데이터를 통해 비가 올지(1) 비가 안올지(0) 을 예측 할것

# Features: random numbers
# 20개의 feature(특성, 독립변수) 랜덤 생성하는 코드를 작성하시오
X = np.random.randn(num_samples, input_features).astype(np.float32)

# Labels: sum of features > 0 => class 1, else class 0
# Please convince yourself this is the real data, while actuall not the case

# Label데이터 생성 비가 올때는 1 비가 안올 때는 0이라는 더미데이터 생성하는 코드
# 아래 코드는 X의 20개의 데이터의 합이 양수면 1 음수면 0이라는 더미데이터를 생성하는 코드이다.
y = (X.sum(axis=1) > 0).astype(np.float32)

# Convert to PyTorch tensors
X_tensor = torch.from_numpy(X)
y_tensor = torch.from_numpy(y).unsqueeze(1)  # Add dimension for compatibility

In [ ]:
print(X[0])
print(y[0])

$x_0 + x_1 + ... + x_{19} >0 $

$$x_0 \cdot w_0 + \cdots + x_{19} \cdot w_{19} + b$$

비가 오는지 오지 않는지 어떻게 추정할 수 있을까? 위 수식을 계산하여 결정한다. 비가 오면 값이 커지고, 비가 오지 않으면 값이 작아지도록 한다. 0을 기준으로 양수이면 비가 오는 것으로 판단, 음수면 비가 오지 않는 것으로 판단한다.

`X`는 주어진 데이터이니, 우리는 원하는 값을 계산할 수 있도록 해 주는 `w`와 `b`의 값을 구하면 된다.

일단 랜덤으로 값을 초기화해 놓고, 이후 경사하강법으로 좋은 값을 찾아간다.

In [48]:
# 위에서 말했든 실제 딥러닝에서도 초기 가중치와 편향 값은 랜덤으로 찍고 시작을 합니다.
# 그리고 기울기 값을 기록하기 위해 requires_grad=True ! 필수!!
# 가중치의 개수는 특성의 개수와 같아야 겠죠? 아래 빈칸을 채워볼까요?
w = torch.randn(input_features, requires_grad=True) 
b = torch.randn(1, requires_grad=True)

- w를 출력해보면 20개의 랜덤값이 있습니다.
- Why?? X의 특성 개수 20개에 각각 다른 가중치를 적용하기 위해 w를 생성할 때 파라미터로 input_features(20)을 넣어주었기 때문입니다.

In [ ]:
w

본격적으로 답을 찾기 전에, 랜덤으로 만든 값들이 얼마나 유용한지 테스트해보자.

혹시라도 랜덤으로 만들었는데 이미 잘 맞춘다면 우리가 이 고생을 할 필요가 없다.

In [ ]:
# 일반적으로 이진분류(O or X)에서 찍는 다고 생각하면 50%의 확률이다
# 아래 코드는 지금 당장은 이해할 필요없고 일단 랜덤으로 찍었을 때 얼마정도의 확률이 나오는지 재미삼아 계산을 해본 것 입니다.
cnt_total = 0
cnt_correct = 0
for x_i, y_i in zip(X_tensor, y_tensor):
    with torch.no_grad():
        score = torch.sum(x_i*w) + b
    predict_flag = score > 0
    answer_flag = y_i == 1

    if predict_flag == answer_flag:
        cnt_correct += 1
    cnt_total += 1

print(f'Accuracy: {cnt_correct/cnt_total}')

다음은 놀랍게도 실제 뉴럴네트워크의 학습 과정이다.
```
면접관: 당신의 장점은?
나: 저는 머신러닝 전문가입니다.
면접관: 9+10은?
나: 3 입니다.
면접관: 틀렸네. 전혀 달라. 답은 19일세.
나: 16 입니다.
면접관: 틀렸네. 답은 19일세.
나: 18 입니다.
면접관: 틀렸네. 답은 19일세.
나: 19 입니다.
면접관: 자넨 합격일세.
```

다만 아래와 같이 좀 더 정확하게 고칠 수 있다.

```
훈련교관: 현재 서울 곳곳의 습도는 이러하다. 1시간 후에 비가 오겠는가?
신경망: 수식을 계산한 결과 8이 나왔습니다. 0보다 크니 비가 올 것입니다.
훈련교관: 답은 비가 오지 않는다네.
신경망: 명심하겠습니다.

훈련교관: 현재 서울 곳곳의 습도는 이러하다. 1시간 후에 비가 오겠는가?
신경망: 수식을 계산한 결과 3이 나왔습니다. 0보다 크니 비가 올 것입니다.
훈련교관: 답은 비가 온다네.
신경망: 명심하겠습니다.

훈련교관: 현재 서울 곳곳의 습도는 이러하다. 1시간 후에 비가 오겠는가? (1. 학습 데이터 샘플링)
신경망: 수식을 계산한 결과 -10이 나왔습니다. 0보다 작으니 비가 안 올 것입니다. (2. 추론)
훈련교관: 답은 비가 오지 않는다네.
신경망: 명심하겠습니다. (3. 손실함수에서 역전파된 그래디언트를 바탕으로 파라미터 조정)
```
위에서 이미 1단계와 2단계를 끝냈다.
이제 위 코드에 약간 추가해 3단계를 수행하자.



손실함수를 계산하기 이전에 손실함수에 대해 짚고 넘어가는 것이 좋겠다. `torch.nn.BCEWithLogitsLoss()`가 우리가 사용할 손실함수다. 이 함수의 수학적 구조에 대해 논하는 것은 이론 시간의 역할이고, 실습 시간에는 이 손실함수가 우리가 원하는 성질을 만족시키는지만 간단히 체크하고 넘어가자.

손실함수는 말 그대로의 의미를 지닌다. 손실이다. 크면 안 된다. 우리는 손실을 줄여야 한다. 좀 더 정확히는, 절대적인 크기보다는 상대적인 크기가 중요하다.

신경망은 학습을 통해 나쁜 상태에서 좋은 상태로 나아간다. 나쁜 상태는 비가 오는지 오지 않는지 잘 예측하지 못하는 상태이고, 좋은 상태는 그 반대다. 현재 신경망이 처한 상태가 얼마나 좋은지, 또는 얼마나 나쁜지 알려주는 가이드가 손실함수다.

우리에게 $s_1$과 $s_2$라는 두 가지의 상태가 있고, $s_1$이 더 바람직한 상태라고 하자. 손실함수를 $f$라고 하면, 다음을 만족해야 한다.

$$f(s_1) < f(s_2)$$

(상태란 단적으로 말하면 `w`와 `b`의 값을 말한다.)

$$x_0 \cdot w_0 + \cdots + x_{19} \cdot w_{19} + b$$

A. 만약 신경망이 수식을 계산한 결과가 10이고, 이 때 비가 온다면 현재 신경망은 좋은 상태에 있는 것이다.

B. 만약 신경망이 수식을 계산한 결과가 10이고, 이 때 비가 오지 않는다면 현재 신경망은 나쁜 상태에 있는 것이다.

C. 만약 신경망이 수식을 계산한 결과가 -6이고, 이 때 비가 온다면 현재 신경망은 나쁜 상태에 있는 것이다.

D. 만약 신경망이 수식을 계산한 결과가 -6이고, 이 때 비가 오지 않는다면 현재 신경망은 좋은 상태에 있는 것이다.


In [ ]:
criterion = torch.nn.BCEWithLogitsLoss() # 분류문제는 이걸쓰는게 좋다
# criterion = torch.nn.MSELoss
# 비가 오면 1, 안 오면 0

# A
a = criterion(torch.tensor([10.]), torch.tensor([1.]))
print(a)
# B
b = criterion(torch.tensor([10.]), torch.tensor([0.]))
print(b)
# C
c = criterion(torch.tensor([-6.]), torch.tensor([1.]))
print(c)
# D
d = criterion(torch.tensor([-6.]), torch.tensor([0.]))
print(d)

assert a < b
assert a < c
assert d < b
assert d < c
# 위 코드에 대한 이해가 어려우시다면 BCEWithLogitsLoss 랴는 손실함수는 숫자가 높으면 yes에 가깝고 숫자가 낮으면 no를
# 뜻한다고 추상적으로 이해를 해봅시다.

손실함수가 원하는 성질을 가진다는 것을 확인했으니 이제 신경망의 학습과정을 구현하자. 학습이 진행되며 손실함수가 점점 줄어들어야 정상이다.

In [ ]:
# 손실함수 정의
# 이진 분류를 수행하는 손실함수 코드를 작성해봅시다.
criterion = torch.nn.BCEWithLogitsLoss()

# 데이터를 몇번 돌려서 학습을 할지 정의
num_epoch = 300

# 아까 봤던
'''
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad
'''
#위 코드 처럼 가중치와 편향의 기울기에 얼만큼의 learning_rate(학습률)을 적용해 얼만큼 많이, 또는 적게 반영할 것인지 정의
learning_rate = 0.003

# 가중치, 편향 초기화
w.grad = torch.zeros_like(w) # Initialize gradient
b.grad = torch.zeros_like(b) # Initialize gradient

for epoch in range(num_epoch):
    loss_sum = 0
    # 자 아까 X_tensor, y_tensor가 뭐였죠? 랜덤하게 생성된 20개의 특성 X_tensor
    # 그리고 랜덤하게 생성된 1(yes), 0(no)의 값 y_tensor 입니다.
    # 아래와 같이 for 문을 작성하면 x_i에는 20개의 특성, y_i에는 0,1중 하나의 값이 들어가겠죠?
    # 아래 ????에 들어가야 할 값은 데이터 입니다!
    for x_i, y_i in zip(X_tensor, y_tensor):
        # Evaluation code is commented out because not needed
        # predict_flag = (x_i*w).sum() + b > 0
        # answer_flag = y_i == 1

        #가중치의 기울기 초기화하는 코드를 작성해보세요
        w.grad.zero_() # Clear gradient
        b.grad.zero_() # Clear gradient

        # score = x_1 * w_1 + x_2 * w_2 + ... + x_19 * w_19 + b
        score = torch.sum(x_i*w) + b
        # 손실함수 계산을 위해 squeeze() 함수로 차원을 맞춥니다.
        loss = criterion(score.squeeze(), y_i.squeeze())
        # 아래는 역전파 코드입니다.
        loss.backward()
        # X_tensor 는 20개의 특성데이터 num_samples(1000개)가 들어가 있습니다.
        # 1000개의 loss를 다 더한 후 1000개로 나누어 평균 loss를 구할 예정입니다.
        loss_sum += loss.item()

        #가중치를 조정할때는  기울기의 계산이 필요하지 않기 때문에 with 구문을 실행
        with torch.no_grad():
            w -= learning_rate * w.grad
            b -= learning_rate * b.grad

    print(f'Epoch {epoch+1}/{num_epoch}, Loss: {loss_sum/num_samples:.6f}')

학습이 어느정도 진행되었으면 정확도를 다시 확인해보자.

In [ ]:
cnt_total = 0
cnt_correct = 0
for x_i, y_i in zip(X_tensor, y_tensor):

    # 평가를 할 때에도 학습을 하는 것이 아니기 때문에 기울기를 기록할 필요 없습니다. 어떤 코드를 작성해야 하죠??
    with torch.no_grad():
        score = torch.sum(x_i*w) + b
    predict_flag = score > 0
    answer_flag = y_i == 1

    if predict_flag == answer_flag:
        cnt_correct += 1
    cnt_total += 1

print(f'Accuracy: {cnt_correct/cnt_total}')

In [ ]:
#데이터 첫번째 샘플을 다음과 같이 출력하면 값이 나온다.
print(X_tensor[0])
print(y_tensor[0])
#위 딥러닝 아키텍쳐를 그려보자면 아래와 같다.

### 위 X_tensor 와 y_tensor 의 첫번째 값을 출력하면

    tensor([ 1.7641,  0.4002,  0.9787,  2.2409,  1.8676, -0.9773,  0.9501, -0.1514,
            -0.1032,  0.4106,  0.1440,  1.4543,  0.7610,  0.1217,  0.4439,  0.3337,
            1.4941, -0.2052,  0.3131, -0.8541])
            
    tensor([1.])

위와 같이 나왔다
위 데이터를 바탕으로 딥러닝 아키텍쳐를 그려보자면 다음과 같은
"히든레이어가 없는" 단일 레이어로 구성된 신경망이라고 볼 수 있다.

<img src='https://drive.google.com/drive-viewer/AKGpihaD8lib2wGDNwkjxbQ9bBGGGG2o-KYN0z_HNIJVzNNSUwVgMLkrlFtpnUQ1WPfc7GPGb5pEPkrMBjVd6m5MKfWNjlYnLlNWIZ0=w2880-h1428-rw-v1' width='500'  border='0'></a>




아래는 같은 문제를 다층 퍼셉트론, `torch.nn.Module`, `torch.optim` 등을 통해 해결한 것이다. 위는 원리를 설명하기 위한 실습이고, 현업에서는 아래와 같은 코드를 작성하는 것이 좋다.

In [ ]:
class SimpleMLP(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
      #파이토치의 뉴럴넷의 기본은 ! 클래스 상속 기능입니다 ! 아래 코드를 작성해주세요!
        super(SimpleMLP, self).__init__()
        # Define layers

        # 레이어를 쌓는곳 위에 예시는 단일레이어 였지만 실제로는 여러개의 hidden 레이어를 쌓아서 사용한다.
        # 아래에는 두개의 레이어를 쌓는 것을 볼 수 있다.
        # 선형 레이어를 쌓는 코드
        self.fc1 = nn.Linear(input_size, hidden_size)  # First fully connected layer
        # 활성화 함수를 이용해 선형식의 한계를 극복해 봅시다 !
        self.relu = nn.ReLU()                 # ReLU activation
        # 두번째 선형 레이어
        self.fc2 = nn.Linear(hidden_size, output_size) # Second fully connected layer

    def forward(self, x):
        # x 가 들어와서 첫번째 히든레이어 통과
        out = self.fc1(x)      # Input to first layer
        # 히든레이어가 통과한 값이 들어와서 ReLU 함수 적용
        out = self.relu(out)   # Apply ReLU
        # ReLU 함수가 적용된 값이 다시 두번째 히든레이어에 들어가고 최종 output인
        # out으로 값을 return
        out = self.fc2(out)    # Output layer
        return out

### 잠깐 ! ReLU 뭐였지??

 - 은닉계층의 활성함수로는 **ReLU** 함수를 주로 사용합니다.

    <img src="https://datadiving.dothome.co.kr/Deep%202-1_3.png" width=600>

In [ ]:
# Create a dataset and data loader
# DataLoader 모듈을 사용하여 데이터를 배치 단위로 나누기 위해 TensorDataset 모듈로 데이터를 묶어줌
dataset = TensorDataset(X_tensor, y_tensor)
batch_size = 32
# 예를들어 X_tensor의 개수가 1000개면 1~32,33~64 이런식으로 나누어서 들어갑니다 !
# 어떤 모듈을 사용해야 할까요?
dataloader = DataLoader(dataset, batch_size=32, shuffle=True)

# dataloader = create_dataset()

# Hyperparameters
input_size = input_features
# 좀 위에 정의했던 단일레이어보다 좀 더 복잡한 연산을 수행하기 위한 히든 사이즈(히든 레이어의 노드개수) 설정
hidden_size = 64
output_size = 1  # Binary classification (1,0 둘 하나가 나오기 때문에 사이즈는 1개)

# Instantiate the model
model = SimpleMLP(input_size, hidden_size, output_size)

# Loss function and optimizer
criterion = nn.BCEWithLogitsLoss(input)  # Combines a sigmoid layer and the BCELoss
# optimizer 를 아래와 같이 정의하면 optimizer 가 model 의 parameters 즉 모든 가중치와 편향을 저장한다.
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Training parameters
num_epochs = 20

# Training loop
for epoch in range(num_epochs):
    for batch_X, batch_y in dataloader:
        # Forward pass
        outputs = model(????)
        loss = ????(????, ????)

        # Backward pass and optimization
        optimizer.????()  # Clear gradients 저장된 모든 파라미터의 기울기 초기화
        loss.????()        # Compute gradients 모든 파라미터의 기울기 계산
        optimizer.????()       # Update weights 기울기를 바탕으로 가중치 업데이트

    # Print loss for every epoch
    print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')

# train()

# Evaluation
model.eval()
with torch.no_grad():
    outputs = model(X_tensor)
    predictions = torch.????(outputs)  # Apply sigmoid to get probabilities
    predicted_classes = (predictions >= 0.5).float()

    # Calculate accuracy
    accuracy = (predicted_classes == y_tensor).float().mean()
    print(f'Accuracy: {accuracy * 100:.2f}%')


In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
import torch.nn.functional as F
import numpy as np

class SimpleMLP(nn.Module):
    def __init__(self, input_size, hidden_size):
        super(SimpleMLP, self).__init__()
        # Define layers
        self.input_size = input_size
        self.fc1 = nn.????(input_size, hidden_size)  # First fully connected layer
        self.relu = nn.????()             # ReLU activation
        self.fc2 = nn.????(hidden_size, 1) # Second fully connected layer

    def forward(self, x):
        out = self.fc1(x)      # Input to first layer
        out = self.relu(out)   # Apply ReLU
        out = self.fc2(out)    # Output layer
        return out

    def create_dataset(self, num_samples = 1000, batch_size = 32):
        # Features: random numbers
        input_features = self.input_size
        X = np.random.randn(num_samples, input_features).astype(np.float32)

        # Labels: sum of features > 0 => class 1, else class 0
        # Please convince yourself this is the real data, while actuall not the case
        y = (X.sum(axis=1) > 0).astype(np.float32)

        # Convert to PyTorch tensors
        X_tensor = torch.from_numpy(X)
        y_tensor = torch.from_numpy(y).unsqueeze(1)  # Add dimension for compatibility

        dataset = TensorDataset(X_tensor, y_tensor)
        dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

        return dataloader

    def train(self, train_data, num_epochs = 20, learning_rate = 0.001, criterion = nn.BCEWithLogitsLoss):
        criterion = criterion()  # Combines a sigmoid layer and the BCELoss
        optimizer = optim.Adam(self.parameters(), lr = learning_rate)

        # Training loop
        for epoch in range(num_epochs):
            for batch_X, batch_y in train_data:
                # Forward pass
                outputs = self(batch_X)
                loss = criterion(outputs, batch_y)

                # Backward pass and optimization
                optimizer.zero_grad()  # Clear gradients
                loss.backward()        # Compute gradients
                optimizer.step()       # Update weights

            # Print loss for every epoch
            print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')

        return model

    def evaluate(self, test_data):
        # self.eval()
        with torch.no_grad():
            accuracy_history = []
            for batch_X, batch_y in test_data:
                outputs = self(batch_X)
                predictions = torch.sigmoid(outputs)
                predicted_classes = (predictions >= 0.5).float()
                accuracy = (predicted_classes == batch_y).float().mean()
                accuracy_history.append(accuracy)
            accuracy = sum(accuracy_history) / len(accuracy_history)
            print(f'Accuracy: {accuracy * 100:.2f}%')
            return accuracy


model = ????(20, 64)
train_dataset = model.????()
test_dataset = model.????()
print(train_dataset)
model.????(train_dataset)
model.????(test_dataset)

TODO: input_size, hidden_size, learning_rate 등의 하이퍼파라미터를 바꿔 가며 최적의 모델을 찾아보세요.

In [ ]:
def hidden_size_candidates():
    return [2**n for n in range(7)]

def learning_rate_candidates():
    return [0.001]

def train_and_eval(hidden_size, learning_rate):
    model = ????(20, hidden_size)
    train_dataset = model.????(1000)
    test_dataset = model.????(100)

    model.????(????, learning_rate = learning_rate)
    evaluation_result = model.????(test_dataset)

    return evaluation_result

def find_hyperparameter():
    hidden_sizes = ????()
    learning_rates = ????()
    result_history = []
    for hidden_size in hidden_sizes:
        for learning_rate in learning_rates:
            eval_result = ????(hidden_size, learning_rate)
            result_history.append((hidden_size, learning_rate, eval_result))
            print(hidden_size, learning_rate, eval_result)
    return max(result_history, key = lambda x:x[2])

find_hyperparameter()


In [ ]:
# write your code here
# 함수 생성

import matplotlib.pyplot as plt

X = [1,2,3,4]
y = [2,4,6,8]
plt.scatter(X, y)
plt.show()

딥러닝으로


1.   선형 회귀 y = 4 + 3x를 해볼 것
  - 맨 처음에는 torch.tensor이용해서 아예 바닥부터 구현
  - 그 이후에 nn.Linear 써서 구현
  - 그 이후에 dataloader 써서 구현
  - batching 구현해보기
  - optimizer 써보기

2. 다 하고 나서 $ y = w_1 x_1  + w_2 x_2  + w_3 x_3 + b$  해볼 것

$ y = (w_1, w_2, w_3) * (x_1, x_2, x_3)^T +b $



In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
import torch.nn.functional as F
import numpy as np
import matplotlib.pyplot as plt
import random

def generate_synthetic_data(n_samples = 1000, x_amplitude = 10, noise_amplitude = 1):
    X = torch.randn(n_samples, 1) * x_amplitude
    noise = torch.randn(n_samples, 1) * noise_amplitude

    y = 4 + 3 * X + noise
    return X, y

X, y = generate_synthetic_data()
print(X.shape, y.shape)

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
import torch.nn.functional as F
import numpy as np
import matplotlib.pyplot as plt
import random

def generate_synthetic_data(n_samples = 1000, x_amplitude = 10, noise_amplitude = 1):
    X = torch.randn(n_samples, 1) * x_amplitude
    noise = torch.randn(n_samples, 1) * noise_amplitude

    y = 4 + 3 * X + noise
    return X, y

X, y = generate_synthetic_data()
print(X.shape, y.shape)

def plot_data(x, y):
    plt.scatter(x, y, alpha = 0.5)
    plt.show()

def plot_loss_history(loss_history):
    plt.plot(range(1, len(loss_history) + 1), loss_history)
    plt.show()

def plot_fitted_line(x, y, y_pred):
    plt.scatter(x, y, alpha = 0.3)
    sorted_line = [(x, y_p) for x, y_p in zip(x, y_pred)]
    sorted_line = sorted(sorted_line, key = lambda x:x[0])
    sorted_x = [e[0] for e in sorted_line]
    sorted_y_pred = [e[1] for e in sorted_line]
    plt.plot(sorted_x, sorted_y_pred, color = 'red')

    plt.show()

class LinearRegressionModel(nn.Module):
    def __init__(self):
        super(LinearRegressionModel, self).__init__()
        self.w = torch.randn(1, 1, requires_grad = True)
        self.b = torch.randn(1, requires_grad = True)
        self.loss = nn.MSELoss()

    def forward(self, X):
        return ????

    def train_model(self, x, y, learning_rate = 0.001, epochs = 20, print_log = True, plot = True):
        # loss_function = nn.MSELoss()
        loss_history = []
        for epoch in range(epochs):
            y_pred = ????(x)
            # print(y_pred, y)
            loss = self.????(y_pred, y)
            loss_history.append(loss.item())

            # compute the gradient of the loss
            loss.????()

            with torch.????():
                self.w -= learning_rate * self.w.grad
                self.b -= learning_rate * self.b.grad

            self.????.grad.zero_()
            self.????.grad.zero_()

            if print_log:
                print(f'[Linear Regression with torch.tensor] Epoch {epoch+1}/{epochs} Loss: {loss.item()}')
        if plot:
            plot_loss_history(loss_history)
        return loss_history

    def evaluate_model(self, x, y):
        with torch.no_grad():
            y_pred = model(x)
            return self.loss(y_pred, y).item()

X, y = ????(noise_amplitude = 1)
test_X, test_y = ????(noise_amplitude = 1)

model = ????()
test_loss_history = []
train_loss_history = []

for epoch in range(200):
    train_loss = model.train(X, y, epochs = 1, print_log = False, plot = False)
    train_loss_history.extend(train_loss)
    test_loss_history.append(model.evaluate(test_X, test_y))

plot_loss_history(train_loss_history)
plot_loss_history(test_loss_history)

print(model.w.item(), model.b.item())


Optimizer를 써서 gradient descent를 해보기 (SGD)


In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
import torch.nn.functional as F
import numpy as np
import matplotlib.pyplot as plt
import random

def generate_synthetic_data(n_samples = 1000, x_amplitude = 10, noise_amplitude = 1):
    X = torch.randn(n_samples, 1) * x_amplitude
    noise = torch.randn(n_samples, 1) * noise_amplitude

    y = 4 + 3 * X + noise
    return X, y

X, y = generate_synthetic_data()
print(X.shape, y.shape)

def plot_data(x, y):
    plt.scatter(x, y, alpha = 0.5)
    plt.show()

def plot_loss_history(loss_history):
    plt.plot(range(1, len(loss_history) + 1), loss_history)
    plt.show()

def plot_fitted_line(x, y, y_pred):
    plt.scatter(x, y, alpha = 0.3)
    sorted_line = [(x, y_p) for x, y_p in zip(x, y_pred)]
    sorted_line = sorted(sorted_line, key = lambda x:x[0])
    sorted_x = [e[0] for e in sorted_line]
    sorted_y_pred = [e[1] for e in sorted_line]
    plt.plot(sorted_x, sorted_y_pred, color = 'red')

    plt.show()

class LinearRegressionModel(nn.????):
    def __init__(self):
        super(LinearRegressionModel, self).__init__()
        self.w = torch.randn(????, ????, requires_grad = True)
        self.b = torch.randn(????, requires_grad = True)
        self.loss = nn.MSELoss()

    def forward(self, X):
        return X @ self.w + self.b

    def train_model(self, x, y, learning_rate = 0.001, epochs = 20, print_log = True, plot = True):
        # loss_function = nn.MSELoss()
        loss_history = []
        for epoch in range(epochs):
            y_pred = ????(x)
            # print(y_pred, y)
            loss = ????.loss(y_pred, y)
            loss_history.append(loss.item())

            # compute the gradient of the loss
            loss.????()

            # with torch.no_grad():
            #     # self.w -= learning_rate * self.w.grad
            #     # self.b -= learning_rate * self.b.grad
            optimizer.????()

            # self.w.grad.zero_()
            # self.b.grad.zero_()
            optimizer.????()

            if print_log:
                print(f'[Linear Regression with torch.tensor] Epoch {epoch+1}/{epochs} Loss: {loss.item()}')
        if plot:
            plot_loss_history(loss_history)
        return loss_history

    def evaluate(self, x, y):
        with torch.no_grad():
            y_pred = model(x)
            return self.loss(y_pred, y).item()

X, y = generate_synthetic_data(noise_amplitude = 1)
test_X, test_y = generate_synthetic_data(noise_amplitude = 1)

model = LinearRegressionModel()
test_loss_history = []
train_loss_history = []

for epoch in range(200):
    train_loss = model.train(X, y, epochs = 1, print_log = False, plot = False)
    train_loss_history.extend(train_loss)
    test_loss_history.append(model.evaluate(test_X, test_y))

plot_loss_history(train_loss_history)
plot_loss_history(test_loss_history)

print(model.layer)


torch.tensor 대신 nn.Linear 써서 해보기

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
import torch.nn.functional as F
import numpy as np
import matplotlib.pyplot as plt
import random

def generate_synthetic_data(n_samples = 1000, x_amplitude = 10, noise_amplitude = 1):
    X = torch.randn(n_samples, 1) * x_amplitude
    noise = torch.randn(n_samples, 1) * noise_amplitude

    y = 4 + 3 * X + noise
    return X, y

X, y = generate_synthetic_data()
print(X.shape, y.shape)

def plot_data(x, y):
    plt.scatter(x, y, alpha = 0.5)
    plt.show()

def plot_loss_history(loss_history):
    plt.plot(range(1, len(loss_history) + 1), loss_history)
    plt.show()

def plot_fitted_line(x, y, y_pred):
    plt.scatter(x, y, alpha = 0.3)
    sorted_line = [(x, y_p) for x, y_p in zip(x, y_pred)]
    sorted_line = sorted(sorted_line, key = lambda x:x[0])
    sorted_x = [e[0] for e in sorted_line]
    sorted_y_pred = [e[1] for e in sorted_line]
    plt.plot(sorted_x, sorted_y_pred, color = 'red')

    plt.show()

class LinearRegressionModel(nn.Module):
    def __init__(self):
        super(LinearRegressionModel, self).__init__()
        # self.w = torch.randn(1, 1, requires_grad = True)
        # self.b = torch.randn(1, requires_grad = True)
        self.layer = nn.????(1, 1)
        self.loss = nn.????()
        self.optimizer = optim.????

    def forward(self, X):
        # return X @ self.w + self.b
        return self.layer(X)

    def train_model(self, x, y, learning_rate = 0.001, epochs = 20, print_log = True, plot = True):
        # loss_function = nn.MSELoss()
        loss_history = []
        optimizer = self.????(????, lr = learning_rate)

        for epoch in range(epochs):
            y_pred = self(x)
            # print(y_pred, y)
            loss = ????
            loss_history.append(loss.item())

            # compute the gradient of the loss
            loss.backward()

            # with torch.no_grad():
            #     # self.w -= learning_rate * self.w.grad
            #     # self.b -= learning_rate * self.b.grad
            optimizer.step()

            # self.w.grad.zero_()
            # self.b.grad.zero_()
            optimizer.zero_grad()

            if print_log:
                print(f'[Linear Regression with torch.tensor] Epoch {epoch+1}/{epochs} Loss: {loss.item()}')
        if plot:
            plot_loss_history(loss_history)
        return loss_history

    def evaluate(self, x, y):
        with torch.no_grad():
            y_pred = model(x)
            return ????

X, y = generate_synthetic_data(noise_amplitude = 1)
test_X, test_y = generate_synthetic_data(noise_amplitude = 1)

model = LinearRegressionModel()
test_loss_history = []
train_loss_history = []

for epoch in range(200):
    train_loss = model.train(X, y, epochs = 1, print_log = False, plot = False)
    train_loss_history.extend(train_loss)
    test_loss_history.append(model.evaluate(test_X, test_y))

plot_loss_history(train_loss_history)
plot_loss_history(test_loss_history)

print(model.layer)


torch DataLoader 써서 데이터 다루기 (자동으로 알아서 batching 해줌!)

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
import torch.nn.functional as F
import numpy as np
import matplotlib.pyplot as plt
import random

def plot_data(x, y):
    plt.scatter(x, y, alpha = 0.5)
    plt.show()

def plot_loss_history(loss_history):
    plt.plot(range(1, len(loss_history) + 1), loss_history)
    plt.show()

def plot_fitted_line(x, y, y_pred):
    plt.scatter(x, y, alpha = 0.3)
    sorted_line = [(x, y_p) for x, y_p in zip(x, y_pred)]
    sorted_line = sorted(sorted_line, key = lambda x:x[0])
    sorted_x = [e[0] for e in sorted_line]
    sorted_y_pred = [e[1] for e in sorted_line]
    plt.plot(sorted_x, sorted_y_pred, color = 'red')

    plt.show()

def generate_synthetic_data(n_samples = 1000, x_amplitude = 10, noise_amplitude = 1, batch_size = 32):
    X = torch.randn(n_samples, 1) * x_amplitude
    noise = torch.randn(n_samples, 1) * noise_amplitude

    y = 4 + 3 * X + noise

    dataset = TensorDataset(X, y)
    dataloader = DataLoader(dataset, batch_size = batch_size, shuffle = True)

    return dataloader

class LinearRegressionModel(nn.Module):
    def __init__(self):
        super(LinearRegressionModel, self).__init__()
        # self.w = torch.randn(1, 1, requires_grad = True)
        # self.b = torch.randn(1, requires_grad = True)
        self.layer = ????
        self.loss = ????
        self.optimizer = ????

    def forward(self, X):
        # X.shape: (batch_size, n_feature)
        # self.layer.shape: (n_feature, hidden_layer)
        # X.shape @ self.layer: (batch_size, hidden_layer)
        # m, n @ n, p -> m, p
        # return X @ self.w + self.b
        return self.????

    def train_model(self, data, learning_rate = 0.001, epochs = 20, print_log = True, plot = True):
        # loss_function = nn.MSELoss()
        loss_history = []
        optimizer = ????

        for epoch in range(epochs):
            for x, y in data:
                y_pred = self(x)

                loss = ????
                loss_history.append(loss.item())

                # compute the gradient of the loss
                loss.????
                optimizer.????
                optimizer.????

            if print_log:
                print(f'[Linear Regression with torch.tensor] Epoch {epoch+1}/{epochs} Loss: {loss.item()}')
        if plot:
            plot_loss_history(loss_history)
        return loss_history

    def evaluate(self, data):
        with torch.no_grad():
            loss_list = []

            for x, y in data:
                y_pred = ????
                loss = ????
                loss_list.append(loss)

            return sum(loss_list) / len(loss_list)

train_data = generate_synthetic_data(noise_amplitude = 1)
test_data = generate_synthetic_data(noise_amplitude = 1)

model = LinearRegressionModel()
test_loss_history = []
train_loss_history = []

for epoch in range(200):
    train_loss = model.train(train_data, epochs = 1, print_log = False, plot = False)
    train_loss_history.extend(train_loss)
    test_loss_history.append(model.evaluate(test_data))

plot_loss_history(train_loss_history)
plot_loss_history(test_loss_history)

print(model.layer)


1. $x+y<1$인지 판별하는
  - 데이터셋을 만들고
  - 뉴럴넷을 자유롭게 여러 형태로 만든 후
  - 학습/평가하고
  - 최종적으로 가장 좋은 뉴럴넷의 성능을 확인해보세요.
2. $x^2+y^2<1$인지 판별하는
  - 데이터셋을 만들고
  - 뉴럴넷을 자유롭게 여러 형태로 만든 후
  - 학습/평가하고
  - 최종적으로 가장 좋은 뉴럴넷의 성능을 확인해보세요.
  



In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
import torch.nn.functional as F
import numpy as np
import matplotlib.pyplot as plt
import random

def plot_data(x, y):
    plt.scatter(x, y, alpha = 0.5)
    plt.show()

def plot_loss_history(loss_history):
    plt.plot(range(1, len(loss_history) + 1), loss_history)
    plt.show()

def generate_artificial_data(n_samples, batch_size = 32):
    x = torch.randn(n_samples, 2)
    y = torch.sum(x**2, dim = 1).unsqueeze(dim = 1)

    y = (y > 1).float()

    dataset = TensorDataset(x, y)
    dataloader = DataLoader(dataset, batch_size = batch_size, shuffle = True)

    return dataloader

class BinaryClassifier(nn.Module):
    def __init__(self, hidden_size):
        super(BinaryClassifier, self).__init__()
        self.layer1 = ????
        self.activation = ????
        self.layer2 = ????
        self.sigmoid = ????
        self.loss = ????
        self.optimizer = ????

    def forward(self, x):
        output = self.???? # output.shape: (batch_size, hidden_size)
        output = self.????
        output = self.???? # output.shape: (batch_size, 1)
        output = self.???? # output.shape: (batch_size, 1)

        return output

    def train_model(self, train_data, valid_data, epochs = 20, learning_rate = 0.002):
        optimizer = ????
        train_loss_history = []
        valid_loss_history = []
        valid_acc_history = []

        for epoch in range(epochs):
            for x, y in train_data:
                y_pred = ????
                loss = ????
                train_loss_history.append(loss.item())

                loss.????
                optimizer.????
                optimizer.????

                acc, valid_loss = self.evaluate_model(valid_data)
                self.train()
                valid_acc_history.append(acc)
                valid_loss_history.append(valid_loss)

            # print(f'{epoch+1}/{epochs} Epoch, train loss = {loss}, valid loss = {valid_loss}, acc = {acc}')

        return train_loss_history, valid_loss_history, valid_acc_history

    def evaluate_model(self, data):
        self.eval()
        with torch.no_grad():
            correct = 0
            total = 0
            loss_history = []
            for x, y in data:
                y_pred = ????
                loss_history.append(self.loss(y, y_pred).item())
                correct += torch.sum(((y_pred > 0.5).float() == y).float())
                total += 32

            return correct / total, sum(loss_history) / len(loss_history)

model = BinaryClassifier(32) #
train_data = generate_artificial_data(1000)
valid_data = generate_artificial_data(100)
test_data = generate_artificial_data(100)

train_loss_history, valid_loss_history, valid_acc_history = model.train_model(train_data, valid_data, epochs = 100)
plot_loss_history(train_loss_history)
plot_loss_history(valid_loss_history)
plot_loss_history(valid_acc_history)

model.evaluate_model(test_data)